trigger:
  - "*"

name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

variables:
  - template: variables/prod.yml

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - template: build.yml

  - stage: CreateServiceBus
    jobs:
      - template: infrastructure.yml
        parameters:
           azureSubscription: ${{variables.azureSubscription}}
           resourceGroupName: "${{variables.resourceGroupName}}"
           serviceBusName: "${{variables.serviceBusName}}"
           queueName: "${{variables.queueName}}"


  - stage: Deploy
    displayName: Deploy
    dependsOn: Build
    condition: succeeded()
    variables:
      - group: WooWebhookReceiver-Common
    jobs:
      - template: deploy.yml
        parameters:
          azureSubscription: ${{variables.azureSubscription}}
          environment: "${{variables.environment}}"
          webappName: "${{variables.webappName}}"
          resourceGroupName: "${{variables.resourceGroupName}}"
          location: "${{variables.location}}"
          appServicePlanName: "${{variables.appServicePlanName}}"
          baseUrl: "${{variables.baseUrl}}"

